apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nessus
  namespace: nessus
  labels:
    app: nessus
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
